# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  host: 127.0.0.1
  username: event_website
  password: event123
  encoding: unicode
  database: my_app_development
  pool: 5

test:
  adapter: postgresql
  host: 127.0.0.1
  username: event_website
  password: event123
  encoding: unicode
  database: my_app_test
  pool: 5

production:
 adapter: postgresql
 encoding: unicode
 host: ec2-23-21-246-25.compute-1.amazonaws.com
 username: yabydnixmxhvho
 password: 636ba331e22274f5565a0075e0a84c62ff030cc7027a3694f80e9dd45dba7bba
 database: d8akhc79fbnfa6
 # http://guides.rubyonrails.org/configuring.html#database-pooling
 pool: 5