# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ca14013f2fe76df503b642e495f122fec93d9e6075668f9e3e681260a0135c72957a18793cffe17e78da77f5d5b26db87a464fb7d81c0789d4ffe3402ed700cd

test:
  secret_key_base: 56f9bfe8e506a09a379882fe9f7f8ef6e190d0e8908db037040f87ca81f5ca7356bf353b37e2de4ddc57fe28e2256f3365a88ecb4c54ee800f9de1e1d17a52ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
